### ISSUE TITLE
Some doubts on the command written in bash for Nopol repair

### ISSUE THREAD

**Issue by DehengYang** [Spirals-Team/defects4j-repair#2]
![2017-10-10 11 38 53](https://user-images.githubusercontent.com/32570286/31368341-ce884b76-adaf-11e7-8ba9-caa5473fd827.png)
As I see from the github page of Nopol, it says the command for Nopol repair requires at least 4 parameters: source path (so that the Nopol can find the source code), class path ( so that Nopol can execute this faulty program), test cases path ( so that Nopol can localize the fault and velidate the patch), and the solver path  (so that Nopol can generate patches).

But in the bash code you display in the picture, it seems there is no test cases path. This is my doubt, could you give me some guidance. Much appreciated for your help.

**Comment by surli** [comment]
You *can* give an explicit test case to Nopol, the execution will be faster but you also can let it find the tests from the classpath. 
The argument is not mandatory.

**Comment by DehengYang** [comment]
Thank you Sir! I will then try the repair command without the parameter of test cases path.
