### ISSUE TITLE
A question about repairing Lang buggy programs with Nopol

### ISSUE THREAD

**Issue by DehengYang** [Spirals-Team/defects4j-repair#3]
When I attempt to repair Lang programs from defects4j, for example, Lang_44, Lang_51, Lang_53 etc. I use the same parameters as that offered by https://github.com/Spirals-Team/defects4j-repair/tree/master/src/bash/nopol-repair/angelic/condition, but I get an unexpected error:

![lang error](https://user-images.githubusercontent.com/32570286/32086854-9cba7246-bb0a-11e7-8382-56c5b0e5efbb.png)

I can use "defects4j compile" "defects4j test" command to compile and test these Lang projects successfully. So I really have no idea why "Syntax error" would happen during the repair process. And I never make any modification about the Lang source codes.

Thanks!

**Comment by tdurieux** [comment]
You have to define the java compliance level to 5.

I recommend using https://github.com/tdurieux/defects4j-repair-runner to run nopol on the defects4j bugs it is easier.
```bash
python defects4j-g5k-node.py -tool Nopol -project Lang -id  44
```
The tool argument can be: Nopol, NopolC, NopolPC, GenProg, Kali, Brutpol, BrutpolC, BrutpolPC

Do not forget to update the Config file: https://github.com/tdurieux/defects4j-repair-runner/blob/master/core/Config.py

To change to tool version you can change the .jar file in `lib` folder
