### ISSUE TITLE
Both human patch and Nopol patch cannot fix the buggy program Chart_3 with 2 failing tests

### ISSUE THREAD

**Issue by DehengYang** [Spirals-Team/defects4j-repair#4]
![twofailedtests](https://user-images.githubusercontent.com/32570286/32705737-204fe7b8-c852-11e7-823b-4cd487fad700.png)

According to "defects4j test", there are two failing tests in Chart_3:
  - org.jfree.data.time.junit.MonthTests::testParseMonth
  - org.jfree.data.time.junit.TimeSeriesTests::testCreateCopy3

But when I apply the human patch or Nopol patch as shown above, the modified program still has one failing test:
- org.jfree.data.time.junit.MonthTests::testParseMonth

Could anyone give some guidance or advice? Thank you so much!

**Comment by monperrus** [comment]
Should you don't "watch" the defects4j-repair repo, here is a question.
Any idea?
Best,
--Martin

**Comment by monperrus** [comment]
Hi Martin
>> According to "defects4j test", there are two failing tests in Chart_3:
>> 
>> 	• org.jfree.data.time.junit.MonthTests::testParseMonth
>> 	• org.jfree.data.time.junit.TimeSeriesTests::testCreateCopy3
I executed Defects4J on my machine and I obtain only one failing test (org.jfree.data.time.junit.TimeSeriesTests::testCreateCopy3), which passes with the Nopol patch. I use JVM 1.7
So, It seems  that the test MonthTests::testParseMonth always fails in his configuration.
I imagine that could be related to the time zone: as de D4J docs says: "Defects4J generates and executes tests in the timezone America/Los_Angeles. If you are using the bugs outside of the Defects4J framework, export the TZ environment variable accordingly."

Related to that, a minor bug from D4J repair repo: for that bug, the failing test cases is duplicated:
https://github.com/Spirals-Team/defects4j-repair/tree/master/results/2015-august#chart-3 <https://github.com/Spirals-Team/defects4j-repair/tree/master/results/2015-august#chart-3>

**Comment by DehengYang** [comment]
Thank you for your great help!
However, I am still having problem when I set the TZ environment on Ubuntu (the command I use is : export TZ="America/Los_Angeles").
![11-14-twofailed](https://user-images.githubusercontent.com/32570286/32761246-2419c594-c8a7-11e7-868c-c23e80196bb0.png)

I still got two failed tests when I test Chart 3. And I also use Java 1.7 version.

Could you give me some advice? Thank you!

**Comment by monperrus** [comment]
Is the problem also due to the language setting? (see https://github.com/SpoonLabs/nopol/issues/143#issuecomment-346334922)
Can we close this issue?

**Comment by DehengYang** [comment]
Yes it is. Thank you!
